/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityDetail: typeof import('./src/components/activities/ActivityDetail.vue')['default']
    ActivityFormFields: typeof import('./src/components/activities/ActivityFormFields.vue')['default']
    ActivityPickList: typeof import('./src/components/controls/ActivityPickList.vue')['default']
    BlockUI: typeof import('primevue/blockui')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    CheckboxGroup: typeof import('./src/components/controls/CheckboxGroup.vue')['default']
    ColorPicker: typeof import('primevue/colorpicker')['default']
    Column: typeof import('primevue/column')['default']
    ConcentrationList: typeof import('./src/components/controls/ConcentrationList.vue')['default']
    ConfirmActionDialog: typeof import('./src/components/base/ConfirmActionDialog.vue')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    CourseConflictList: typeof import('./src/components/controls/CourseConflictList.vue')['default']
    CourseDetail: typeof import('./src/components/courses/CourseDetail.vue')['default']
    CourseFormFields: typeof import('./src/components/courses/CourseFormFields.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    DayGapList: typeof import('./src/components/controls/DayGapList.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DownloadMenu: typeof import('./src/components/base/DownloadMenu.vue')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    HierarchySelector: typeof import('./src/components/controls/HierarchySelector.vue')['default']
    ImportDialog: typeof import('./src/components/base/ImportDialog.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LecturerDetail: typeof import('./src/components/lecturers/LecturerDetail.vue')['default']
    LecturerFormFields: typeof import('./src/components/lecturers/LecturerFormFields.vue')['default']
    LoadingOverlay: typeof import('./src/components/base/LoadingOverlay.vue')['default']
    Message: typeof import('primevue/message')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    Password: typeof import('primevue/password')['default']
    PickList: typeof import('primevue/picklist')['default']
    ProdiFormFields: typeof import('./src/components/prodis/ProdiFormFields.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RepeatableRows: typeof import('./src/components/controls/RepeatableRows.vue')['default']
    ResourceListLayout: typeof import('./src/components/base/ResourceListLayout.vue')['default']
    ResourceTable: typeof import('./src/components/base/ResourceTable.vue')['default']
    ResultActions: typeof import('./src/components/results/ResultActions.vue')['default']
    RoomDetail: typeof import('./src/components/rooms/RoomDetail.vue')['default']
    RoomFormFields: typeof import('./src/components/rooms/RoomFormFields.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SemesterActions: typeof import('./src/components/semesters/SemesterActions.vue')['default']
    SemesterConflictList: typeof import('./src/components/controls/SemesterConflictList.vue')['default']
    SettingFormFields: typeof import('./src/components/settings/SettingFormFields.vue')['default']
    SplitButton: typeof import('primevue/splitbutton')['default']
    TimeRangeList: typeof import('./src/components/controls/TimeRangeList.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    Tree: typeof import('primevue/tree')['default']
    UserFormFields: typeof import('./src/components/users/UserFormFields.vue')['default']
  }
}
