/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    ConfirmActionDialog: typeof import('./src/components/base/ConfirmActionDialog.vue')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DownloadMenu: typeof import('./src/components/base/DownloadMenu.vue')['default']
    ImportDialog: typeof import('./src/components/base/ImportDialog.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoadingOverlay: typeof import('./src/components/base/LoadingOverlay.vue')['default']
    Message: typeof import('primevue/message')['default']
    Password: typeof import('primevue/password')['default']
    ResourceListLayout: typeof import('./src/components/base/ResourceListLayout.vue')['default']
    ResourceTable: typeof import('./src/components/base/ResourceTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('primevue/toast')['default']
  }
}
