/** Barrel for all domain service modules. */
export { lecturersService } from './lecturers'
export { lecturerTimesService } from './lecturerTimes'
export { jurusansService } from './jurusans'
export { konsentrasiService } from './konsentrasi'
export { coursesService } from './courses'
export { roomsService } from './rooms'
export { activitiesService } from './activities'
export { activityConstraintsService } from './activityConstraints'
export type { ActivityConstraintItem } from './activityConstraints'
export { settingsService } from './settings'
export { semestersService } from './semesters'
export { resultsService } from './results'
export { roomTypesService } from './roomTypes'
export { activityTypesService } from './activityTypes'
export { usersService } from './users'
export { timetableService } from './timetable'
