/** Barrel for all domain DTOs. Import from `@/types`. */
export * from './common'
export * from './user'
export * from './lecturer'
export * from './course'
export * from './room'
export * from './activity'
export * from './setting'
export * from './semester'
export * from './result'
export * from './jurusan'
export * from './roomType'
export * from './activityType'
export * from './schedule'
